language: node_js
# whitelist branches
branches:
  only:
    - master
node_js:
  # - "0.11"
  - "0.10"
matrix:
  # allow_failures:
  #   - node_js: "0.11"
  fast_finish: true
script: "npm test"
# after_script: "cat ./coverage/lcov.info | coveralls"
